  default: &default
    adapter: mysql2
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: <%= ENV["USERNAME"] %>
    password: <%= ENV["PASSWORD"] %>
    host: <%= ENV["HOT"] %>

  development:
    <<: *default
    database: <%= ENV["DATABASE"] %>

  test:
    <<: *default
    database: <%= ENV["DATABASE_TEST"] %>

  production:
    <<: *default
    database: <%= ENV["DATABASE_PRODUCTION"] %>
