enabled_locales: ["en", "ja"]
size:
  length_name_category: 100
  length_name: 255
  length_name_description: 2000
  size_image: [80, 100]
  size_page: 8
  limit: 10
  picture_size: 5
  min_quantity: 1
  min_price: 0
  min_hot: 1
  max_hot: 10
  count_new: 4
  count_hot: 4
  min_password: 6
  max_fullname: 50
  max_address: 255
  max_phone: 15
  max_quantity: 11
  max_email: 200
  status: 0
account_type:
  admin: "admin"
curr_unit:
  price: USD
reload_page: "location.reload()"
