enabled_locales: ["en", "ja"]
size:
  length_name_category: 100
  length_name: 255
  length_name_description: 2000
  size_image: [80, 100]
  size_page: 8
  limit: 10
  picture_size: 5
  min_quantity: 1
  min_price: 0
  min_hot: 1
  max_hot: 10
client:
  minimum: 6
  maximum1: 50
  maximum2: 255
  maximum3: 15
  maximum3: 11
account_type:
  admin: "admin"
curr_unit:
  price: USD
